# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Portfolio-CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup nodejs
      uses: actions/setup-node@v3.7.0
      with:
        node-version: "18"
        #cache: 'npm'
    - name: Install deps
      run: npm i
    - name: Build app bundle
      run: npm run build:prod
    - name: Rename index
      run: cp dist/my-portfolio/index.html dist/my-portfolio/404.html
    - name: Deploy to gitHub Pages
      uses: crazy-max/ghaction-github-pages@v3.1.0
      with: 
        build_dir: dist/my-portfolio
      env: 
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
